# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-03 14:04
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('profile_photo', imagekit.models.fields.ProcessedImageField(blank=True, upload_to='blog/post/%Y/%m/%d', verbose_name='프로필 사진')),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(help_text='핸드폰 번호를 입력해 주세요.', max_length=128)),
                ('birthday', models.DateTimeField(default=False, verbose_name='생일')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.CustomUser')),
            ],
        ),
    ]
