# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-21 16:05
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=100, verbose_name='제목')),
                ('content', models.TextField(help_text='Markdown 문법을 적용해 주세요')),
                ('tags', models.CharField(blank=True, max_length=100)),
                ('lnglat', models.CharField(help_text='경도,위도 포맷으로 입력해주세요.', max_length=50, validators=[blog.models.lnglat_validator])),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
