# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-31 13:13
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_thumbnail',
            field=imagekit.models.fields.ProcessedImageField(default='', upload_to='blog/post/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
